### ISSUE TITLE
onepps_ctrl.v and g_timed_cmd.v sources not included

### ISSUE THREAD

**Issue by GuitarSnoopy** [xtrx-sdr/fpga-source#3]
The onepps_ctrl and g_timed_cmd modules in xtrx_peripherals.v have been disabled by the xtrxr4_top.tcl script but we would potentially like to implement the functionality. The 29 Oct 2020 FPGA source code drop does not include onepps_ctrl.v or g_timed_cmd.v. Are they available?

**Comment by chemeris** [comment]
They are not currently available, unfortunately. If you implement them - please consider submitting them as a contribution to the project.
